version: '2.4'

services:
    traffic_light_detector:
        image: toshikinakamura/traffic_light_detector:emergency
        ipc: host
        network_mode: host
        runtime: nvidia
        volumes:
            - ~/catkin_ws/src/traffic_light_detector:/home/amsl/catkin_ws/src/traffic_light_detector
        command: ./launch.sh
