version: '3'

services:
    traffic_light_detector:
        image: traffic_light_detector:tmp
        ipc: host
        network_mode: host
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        volumes:
          - /home/amsl/catkin_ws/src/traffic_light_detector:/home/amsl/catkin_ws/src/traffic_light_detector
        command: ./launch.sh
        # runtime: nvidia
